name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: neuman314/pasteybin-builder:latest
        build-args: |
          ARG1=${{secrets.DOCKERHUB_USERNAME }}
          ARG2=${{secrets.DOCKERHUB_TOKEN }}
